# CocoaPods
set -x COCOAPODS_DISABLE_STATS 1

# Homebrew
set -x HOMEBREW_NO_ANALYTICS 1
set -x HOMEBREW_NO_AUTO_UPDATE 1
set -x HOMEBREW_NO_ENV_HINTS 1

# Fastlane
set -x ASTLANE_OPT_OUT_USAGE 1
set -x FASTLANE_SKIP_UPDATE_CHECK 1
